/************************************************************************//**
 * \file  tim_evt.c
 * \brief Runs disk_timerproc() each millisecond. Also allows to generate
 * timer based system events.
 *
 * \author Jesus Alonso Fernandez (doragasu)
 * \note This module uses TIMER4.
 * \warning Temporizations may not be very accurate!
 * \license GPL-3.0+ <http://www.gnu.org/licenses/gpl.html>
 *****************************************************************************/
/* This file is part of BALSAMO source package.
 *
 * BALSAMO is free software: you can redistribute
 * it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * Some open source application is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with BALSAMO.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "tim_evt.h"
#include <p30f6014.h>
#include "fatfs/diskio.h"

/// Events that each timer will generate when it timeouts.
static SysEvent evt[TIM_EVT_N_TIMERS];
/// Count of each defined timer.
static unsigned int countMs[TIM_EVT_N_TIMERS];


/************************************************************************//**
 * \brief TimEvtInit: Initializes the module.
 ****************************************************************************/
void TimEvtInit(void)
{
	unsigned char i;

	/// Initialize events and counts to 0
	for (i = 0; i < TIM_EVT_N_TIMERS; i++)
	{
		evt[i] = 0;
		countMs[i] = 0;
	}

	/// Start Timer4 in interval time of 1ms
	/// \todo Enlarge timeout to 10 or even 100 ms
	PR4 = FCY / 1000;	// 5530 cycles (+6,25 sec/day)
	T4CON = 0x8000;		// TON, no prescaler
	/// Enable Timer4 interrupt.
	_T4IE = 1;
}

/************************************************************************//**
 * \brief TimEvtConfig: Sets the system event generated by the module.
 *
 * \param[in] nTimer Timer number to set event.
 * \param[in] event Event to generate when the Timer reaches count.
 ****************************************************************************/
void TimEvtConfig(unsigned char nTimer, SysEvent event)
{
	evt[nTimer] = event;
}

/************************************************************************//**
 * \brief TimEvtRun: Starts a N ms count.
 *
 * \param[in] nTimer Timer number to set count.
 * \param[in] delayMs Number of milliseconds to count before generating an
 *            event.
 ****************************************************************************/
void TimEvtRun(unsigned char nTimer, unsigned int delayMs)
{
	countMs[nTimer] = delayMs;
}

/************************************************************************//**
 * \brief TimEvtStop: Stops an already running timer count.
 *
 * \param[in] nTimer Timer number to stop.
 ****************************************************************************/
void TimEvtStop(unsigned char nTimer)
{
	countMs[nTimer] = 0;
}

/************************************************************************//**
 * \brief _T4Interrupt: Timer 4 interrupt routine.
 ****************************************************************************/
void __attribute__((__interrupt__)) _T4Interrupt(void)
{
	unsigned char i;

	/// Clear interrupt flag
	_T4IF = 0;
	/// Call fatfs disk_timerproc() routine
	disk_timerproc();
	/// Check if we have to generate a system event
	for (i = 0; i < TIM_EVT_N_TIMERS; i++)
	{
		if (countMs[i])
		{
			countMs[i]--;
			if (!countMs[i]) SysIQueuePut(evt[i]);
		}
	}
}
